### ISSUE TITLE
src/sys-mysql-sql-reject.c:26:18: fatal error: pcap.h: No such file or directory

### ISSUE THREAD

**Issue by hadesfeng** [arstercz/sys-toolkit#1]
gcc -g -Wall -o sys-mysql-sql-reject -lpcap sys-mysql-sql-reject.c 这个命令报的错误
src/sys-mysql-sql-reject.c:26:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
                  ^
compilation terminated.

**Comment by arstercz** [comment]
你好, 安装 `libpcap-devel` 包就可以解决这个错误.
